

[ missionNamespace, [
"ACE_VMM3",
"ACE_VMH3",
"rhs_weap_m4a1_carryhandle_m203S",
"rhs_weap_m4a1_carryhandle_m203",
"rhs_weap_m4a1_carryhandle_pmag",
"rhs_weap_m27iar",
"rhs_weap_m27iar_grip",
"rhs_weap_m16a4_carryhandle",
"rhs_weap_m16a4",
"rhs_weap_m16a4_carryhandle_M203",
"hlc_rifle_awmagnum",
"hlc_rifle_awMagnum_OD_ghillie",
"hlc_m249_pip1",
"hlc_m249_pip3",
"hlc_lmg_mk48mod1",
"CUP_lmg_m249_pip1",
"hlc_lmg_mg42kws_b",
"CUP_launch_Javelin",
"CUP_launch_Mk153Mod0",
"CUP_launch_M136",
"CUP_launch_FIM92Stinger",
"RH_m9",
"RH_g19",
"RH_m1911",
"RH_Mk11",
"srifle_DMR_02_F",
"srifle_DMR_06_olive_F"], true] call BIS_fnc_addVirtualWeaponCargo;
[ missionNamespace, [
"hlc_30rnd_556x45_SOST",
"hlc_30rnd_556x45_SPR",
"hlc_200rnd_556x45_T_SAW",
"hlc_200rnd_556x45_B_SAW",
"hlc_200rnd_556x45_M_SAW",
"hlc_200Rnd_792x57_T_MG42",
"hlc_200Rnd_792x57_B_MG42",
"hlc_5rnd_300WM_FMJ_AWM",
"hlc_5rnd_300WM_mk248_AWM",
"hlc_5rnd_300WM_BTSP_AWM",
"hlc_5rnd_300WM_AP_AWM",
"hlc_5rnd_300WM_SBT_AWM",
"hlc_5rnd_300WM_T_AWM",
"hlc_200rnd_556x45_M_SAW",
"hlc_200rnd_556x45_B_SAW",
"hlc_200rnd_556x45_T_SAW",
"hlc_200rnd_556x45_Mdim_SAW",
"hlc_100Rnd_762x51_M_M60E4",
"hlc_100Rnd_762x51_B_M60E4",
"hlc_100Rnd_762x51_Barrier_M60E4",
"hlc_100Rnd_762x51_T_M60E4",
"hlc_100Rnd_762x51_Mdim_M60E4",
"CUP_Javelin_M",
"CUP_SMAW_HEAA_M",
"CUP_SMAW_HEDP_M",
"ACE_PreloadedMissileDummy_CUP",
"CUP_Stinger_M",
"RH_15Rnd_9x19_M9",
"RH_17Rnd_9x19_g17",
"RH_7Rnd_45cal_m1911",
"10Rnd_338_Mag",
"ACE_10Rnd_338_API526_Mag",
"ACE_10Rnd_338_300gr_HPBT_Mag",
"ACE_20Rnd_762x51_Mk316_Mod_0_Mag",
"ACE_20Rnd_762x51_M118LR_Mag",
"ACE_20Rnd_762x51_Mk319_Mod_0_Mag",
"ACE_20Rnd_762x51_M993_AP_Mag",
"CUP_1Rnd_HEDP_M203",
"CUP_1Rnd_HE_M203",
"CUP_1Rnd_StarFlare_Red_M203",
"ACE_HuntIR_M203",
"1Rnd_SmokeRed_Grenade_shell",
"1Rnd_Smoke_Grenade_shell",
"HandGrenade",
"ACE_M84",
"SmokeShellRed",
"SmokeShell",
"DemoCharge_Remote_Mag",
"ATMine_Range_Mag",
"SatchelCharge_Remote_Mag"], true] call BIS_fnc_addVirtualMagazineCargo;
[ missionNamespace, [
"ACE_TacticalLadder_Pack",
"ace_gunbag",
"ace_gunbag_Tan",
"ACE_NonSteerableParachute",
"B_AssaultPack_rgr",
"B_Carryall_oli",
"B_FieldPack_oli",
"B_Kitbag_rgr",
"B_Parachute"], true] call BIS_fnc_addVirtualBackpackCargo;
[ missionNamespace, [

"usm_bdu_w",
"usm_bdu_odg",
"U_B_CombatUniform_wdl_w",
"U_B_CombatUniform_wdl_tshirt_w",
"U_B_CombatUniform_wdl_vest_w",
"U_B_CombatUniform_sgg_vest_s",
"U_B_FullGhillie_lsh",
"U_B_PilotCoveralls",
"U_B_HeliPilotCoveralls",

"V_PlateCarrier1_rgr",
"V_PlateCarrier2_rgr",
"usm_vest_rba_lbe_gr",
"usm_vest_rba_lbv_gr",
"usm_vest_rba_lbv_mg",
"usm_vest_rba_lbe_rm",
"usm_vest_rba_lbv_rmp",

"H_Bandanna_sgg",
"H_Watchcap_camo",
"H_Booniehat_oli",
"H_HelmetCrew_B",
"H_PilotHelmetHeli_B",
"FP_Helmet_M81",
"usm_helmet_pasgt_w",
"usm_bdu_8point_wdl",

"G_Aviator",
"G_Bandanna_aviator",
"G_Bandanna_oli",
"G_Bandanna_khk",
"G_Balaclava_blk",
"G_Balaclava_oli",
"G_Combat",
"G_Balaclava_combat",
"CUP_RUS_Balaclava_grn",
"CUP_RUS_Balaclava_blk",
"G_Lady_Blue",

"NVGoggles",
"NVGoggles_OPFOR",
"NVGoggles_INDEP",
"ACE_NVG_Gen1",
"ACE_NVG_Gen2",
"ACE_NVG_Gen2",
"ACE_NVG_Wide",
"CUP_NVG_PVS7",

"Binocular",
"Rangefinder",
"Laserdesignator",
"Laserdesignator_02",
"Laserdesignator_02_ghex_F",
"Laserdesignator_03",
"Laserdesignator_01_khk_F",  // Import the Standard Vanilla Binoculars
"ACE_VectorDay",
"ACE_Vector",
"ACE_Yardage450",

"ItemMap",
"ItemGPS",
"ItemRadio",
"ItemCompass",
"ItemWatch",
"MineDetector",
"ToolKit",
"B_UavTerminal",
"O_UavTerminal",
"I_UavTerminal",   // Import the vanilla Items
"ACE_Altimeter",
"ACE_RangeTable_82mm",
"ACE_ATragMX",
"ACE_fieldDressing",
"ACE_bloodIV_500",
"ACE_bloodIV_250",
"ACE_bloodIV",
"ACE_CableTie",
"ACE_DAGR",
"ACE_DefusalKit",
"ACE_EntrenchingTool",
"ACE_epinephrine",
"ACE_Flashlight_MX991",
"ACE_IR_Strobe_Item",
"ACE_Flashlight_KSF1",
"ACE_Kestrel4500",
"ACE_M26_Clacker",
"ACE_Clacker",
"ACE_Flashlight_XL50",
"ACE_MapTools",
"ACE_microDAGR",
"ACE_morphine",
"ACE_RangeCard",
"ACE_Sandbag_empty",
"ACE_SpottingScope",
"ACE_Tripod",
"ACE_UAVBattery",
"ACE_wirecutter",
"ACE_SpraypaintBlack",
"ACE_SpraypaintBlue",
"ACE_SpraypaintGreen",
"ACE_SpraypaintRed",
"ACE_bodyBag",
"ACE_HuntIR_monitor",       // Import the common ACE Items
"ACRE_PRC117F",
"ACRE_PRC148",
"ACRE_PRC152",
"ACRE_PRC343",
"ACRE_PRC77",
"ACRE_SEM52SL",

"R3F_APAV40",
"R3F_AC58",
"R3F_FUM40",
"R3F_ECL40",
"ACE_muzzle_mzls_B",

"RH_m110sd",
"muzzle_snds_M",
"muzzle_snds_H_MG",
"muzzle_snds_H_MG_blk_F",
"hlc_muzzle_556NATO_KAC",

"RH_gemtech9",
"RH_X300",

"RH_anpvs4",
"RH_anpvs10",

"optic_Arco_blk_F",
"optic_Arco",
"optic_ERCO_blk_F",
"optic_ERCO_khk_F",
"optic_Hamr_khk_F",
"optic_SOS",

"RH_barska_rds",
"optic_DMS",
"CUP_optic_Elcan_reflex",
"RH_eotech553",
"optic_KHS_blk",
"RH_LTdocter",
"RH_leu_mk4",
"optic_LRPS",
"rhsusf_acc_ELCAN",
"rhsusf_acc_elcan_3d",
"rhsusf_acc_ACOG",
"rhsusf_acc_ACOG_3d",
"rhsusf_acc_eotech_552",
"rhsusf_acc_compm4",
"optic_Hamr",
"rhsusf_acc_SpecterDR",
"rhsusf_acc_SpecterDR_3d",
"RH_reflex",
"ACE_acc_pointer_green",
"acc_pointer_IR",
"RH_SFM952V",
"rhsusf_acc_grip2",
"rhsusf_acc_grip1",
"RH_HBLM",
"bipod_01_F_blk"], true] call BIS_fnc_addVirtualItemCargo;