

[ missionNamespace, [
"ACE_VMM3",
"ACE_VMH3",
"CUP_launch_RPG7V",
"CUP_launch_Metis",
"CUP_launch_9K32Strela",
"CUP_launch_RPG18",
"CUP_launch_Igla",
"CUP_smg_bizon",
"CUP_srifle_ksvk",
"CUP_srifle_SVD",
"hlc_rifle_aek971",
"hlc_rifle_ak74",
"hlc_rifle_ak74_dirty",
"hlc_rifle_aks74",
"hlc_rifle_aks74_GL",
"hlc_rifle_aks74u",
"hlc_rifle_akmgl",
"hlc_rifle_akm",
"hlc_rifle_akms",
"hlc_rifle_rpk",
"hlc_rifle_rpk74n",
"RH_mak",
"RH_tt33",
"RH_vz61",
"str_oc_kipa",
"str_pkm",
"str_pp_90m1",
"str_rpd",
"str_sks_old",
"str_as_val",
"str_ngn",
"str_vss_vinl"], true] call BIS_fnc_addVirtualWeaponCargo;
[ missionNamespace, [
"hlc_30Rnd_762x39_b_ak",
"hlc_30Rnd_762x39_t_ak",
"hlc_45Rnd_762x39_m_rpk",
"hlc_45Rnd_762x39_t_rpk",
"hlc_30rnd_762x39_s_ak",
"hlc_30Rnd_545x39_B_AK",
"hlc_30Rnd_545x39_t_ak",
"hlc_30Rnd_545x39_EP_ak",
"hlc_30Rnd_545x39_S_AK",
"hlc_45Rnd_545x39_t_rpk",
"CUP_64Rnd_9x19_Bizon_M",
"ACE_Chemlight_HiOrange",
"ACE_Chemlight_HiRed",
"ACE_Chemlight_HiYellow",
"ACE_Chemlight_HiWhite",
"ACE_Chemlight_Orange",
"ACE_Chemlight_White",
"ACE_HandFlare_White",
"ACE_HandFlare_Red",
"ACE_HandFlare_Green",
"ACE_HandFlare_Yellow",
"CUP_64Rnd_Green_Tracer_9x19_Bizon_M",
"5rnd_762_mos",
"CUP_5Rnd_127x108_KSVK_M",
"30rnd_mag_kedr",
"30rnd_mag_trs_kedr",
"100rnd_korob_pkp",
"100rnd_korob_trs_pkp",
"200rnd_korob_pkp",
"64rnd_9mm_90m1",
"100rnd_korob_trs_rpd",
"100rnd_korob_rpd",
"10rnd_sks_mag",
"CUP_10Rnd_762x54_SVD_M",
"20rnd_mag_vss_doz",
"10rnd_mag_vss_doz_trs",
"10rnd_mag_vss_sz_trs",
"20rnd_mag_vss_sz",
"30rnd_mag_vss_doz",
"30rnd_mag_vss_sz",
"ACE_PreloadedMissileDummy_CUP",
"ACE_PreloadedMissileDummy_RPG18_CUP",
"RH_8Rnd_762_tt33",
"RH_8Rnd_9x18_Mak",
"7Rnd_nagan_rev",
"RH_20Rnd_32cal_vz61",
"hlc_VOG25_AK",
"CUP_IlumFlareRed_GP25_M",
"CUP_OG7_M",
"CUP_PG7V_M",
"CUP_PG7VM_M",
"CUP_PG7VL_M",
"CUP_AT13_M",
"CUP_Igla_M",
"CUP_Strela_2_M",
"CUP_HandGrenade_RGD5",
"SmokeShellRed",
"SmokeShell",
"DemoCharge_Remote_Mag",
"ATMine_Range_Mag",
"SatchelCharge_Remote_Mag"], true] call BIS_fnc_addVirtualMagazineCargo;
[ missionNamespace, [
"ACE_TacticalLadder_Pack",
"ace_gunbag",
"ace_gunbag_Tan",
"ACE_NonSteerableParachute",
"CUP_B_CivPack_WDL",
"B_Carryall_oli",
"CUP_B_HikingPack_Civ",
"CUP_B_RPGPack_Khaki",
"B_Parachute"], true] call BIS_fnc_addVirtualBackpackCargo;
[ missionNamespace, [

"CUP_U_O_CHDKZ_Kam_01",
"CUP_U_O_CHDKZ_Kam_03",
"CUP_U_O_CHDKZ_Kam_04",
"CUP_U_O_CHDKZ_Kam_05",
"CUP_U_O_CHDKZ_Kam_06",
"CUP_U_O_CHDKZ_Kam_07",
"CUP_U_O_CHDKZ_Commander",
"CUP_U_O_Pilot_01",


"CUP_V_O_Ins_Carrier_Rig",
"CUP_V_O_Ins_Carrier_Rig_Light",
"CUP_V_O_Ins_Carrier_Rig_Com",
"CUP_V_O_Ins_Carrier_Rig_MG",

"CUP_H_ChDKZ_Beanie",
"CUP_H_ChDKZ_Cap",
"CUP_H_ChDKZ_Beret",
"CUP_H_TK_TankerHelmet",
"H_Cap_headphones",

"G_Balaclava_oli",
"G_Aviator",
"G_Bandanna_oli",
"G_Bandanna_khk",
"G_Balaclava_blk",
"G_Balaclava_oli",

"Binocular",

"ItemMap",
"ItemRadio",
"ItemCompass",
"ItemWatch",
"MineDetector",
"ToolKit",   // Import the vanilla Items
"ACE_RangeTable_82mm",
"ACE_fieldDressing",
"ACE_bloodIV_500",
"ACE_bloodIV_250",
"ACE_bloodIV",
"ACE_CableTie",
"ACE_DefusalKit",
"ACE_EntrenchingTool",
"ACE_epinephrine",
"ACE_Flashlight_MX991",
"ACE_Flashlight_KSF1",
"ACE_M26_Clacker",
"ACE_Clacker",
"ACE_Flashlight_XL50",
"ACE_MapTools",
"ACE_morphine",
"ACE_RangeCard",
"ACE_Sandbag_empty",
"ACE_SpottingScope",
"ACE_Tripod",
"ACE_wirecutter",
"ACE_SpraypaintBlack",
"ACE_SpraypaintBlue",
"ACE_SpraypaintGreen",
"ACE_SpraypaintRed",
"ACE_bodyBag",       // Import the common ACE Items
"ACRE_PRC117F",
"ACRE_PRC152",
"ACRE_PRC77",
"ACRE_PRC148",
"ACRE_PRC343",



"R3F_APAV40",
"R3F_AC58",
"R3F_FUM40",
"R3F_ECL40",
"RH_HBLM",
"RH_pmsd",
"hlc_muzzle_545SUP_AK",
"hlc_muzzle_762SUP_AK",

"CUP_optic_NSPU_RPG",
"optic_Aco",
"ACE_acc_pointer_green",
"acc_flashlight",

"hlc_optic_kobra"], true] call BIS_fnc_addVirtualItemCargo;